# This file was generated by GoReleaser. DO NOT EDIT.
cask "wxcli" do
  name "wxcli"
  desc "A fast CLI for managing WeChat Official Account"
  homepage "https://github.com/inforix/wxcli"
  version "1.0.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wxcli"

  on_macos do
    on_intel do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_darwin_amd64.tar.gz"
      sha256 "be60087c37250fe4f791cdcef597441eee0facd4ed17c81a03730ef3a51c15c8"
    end
    on_arm do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_darwin_arm64.tar.gz"
      sha256 "6cf38e7303d4c5099ceb30f70ae72b7a8e7b178e476c19704524054091471575"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_linux_amd64.tar.gz"
      sha256 "f36f6211bdafa86aa06b487a1dd98b12b6823012257068dec2ffdcce1769fd47"
    end
    on_arm do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_linux_arm64.tar.gz"
      sha256 "58690e743511ea5d26f1e102cd9fd8bd50fe6fa047ad83b8d43c42f6d1f33810"
    end
  end

  # No zap stanza required
end
