# This file was generated by GoReleaser. DO NOT EDIT.
cask "wxcli" do
  name "wxcli"
  desc "A fast CLI for managing WeChat Official Account"
  homepage "https://github.com/inforix/wxcli"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wxcli"

  on_macos do
    on_intel do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_darwin_amd64.tar.gz"
      sha256 "5b5668fdbb30ea4024aab5ad505a299480eb8397f4fa9a1a458a5578b641b50b"
    end
    on_arm do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_darwin_arm64.tar.gz"
      sha256 "8159983e3b5987b42b879afdb23330d341a26e5fd3a359aa48f3efd368923386"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_linux_amd64.tar.gz"
      sha256 "6a761aa09bb477b694aebcca3714e102ff3fcc08f7b48c0be5260b957b640fca"
    end
    on_arm do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_linux_arm64.tar.gz"
      sha256 "2139ae174c8b7550d2ef5c81e6fbce1d9402a3e2b5ccdeafd95b44b1bcacabe5"
    end
  end

  # No zap stanza required
end
