# This file was generated by GoReleaser. DO NOT EDIT.
cask "wxcli" do
  name "wxcli"
  desc "A fast CLI for managing WeChat Official Account"
  homepage "https://github.com/inforix/wxcli"
  version "1.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wxcli"

  on_macos do
    on_intel do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_darwin_amd64.tar.gz"
      sha256 "0d3628185ad486edbead934508cfb64405db43a6a5c99ad2f318236dd5699e4b"
    end
    on_arm do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_darwin_arm64.tar.gz"
      sha256 "b1919aa6114c52d80b8982f9b146e9c9aaa240c4990ecc926a1bf1f0d0f670b5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_linux_amd64.tar.gz"
      sha256 "b7beaefc26dea3b075b856e9bba251ba0865fb93a09730454874c6c600c9693a"
    end
    on_arm do
      url "https://github.com/inforix/wxcli/releases/download/v#{version}/wxcli_#{version}_linux_arm64.tar.gz"
      sha256 "3f1bd136e18b504df8a8104122cdbb11d614ac418c217d93fa5fe894eedf0a43"
    end
  end

  # No zap stanza required
end
